version: '3.1'

services:

  beacon:
    ports: !reset [] 
    expose: [ 5050 ]

  permissions:
    ports: !reset []
    expose: [ 5051 ]

  frontend:
    ports: !reset [] 
    expose: [ 3000 ]
    networks:
      - my-app-network      
